CREATE SCHEMA IF NOT EXISTS chat;

CREATE TABLE IF NOT EXISTS chat.users (
	id SERIAL PRIMARY KEY,
	login TEXT NOT NULL UNIQUE,
	password TEXT
);

CREATE TABLE IF NOT EXISTS chat.chatrooms (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	owner INT NOT NULL REFERENCES chat.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat.users_chatrooms (
	userID INT NOT NULL REFERENCES chat.users(id) ON DELETE CASCADE,
	chatroomID INT NOT NULL REFERENCES chat.chatrooms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat.messages (
	id SERIAL PRIMARY KEY,
	authorID INT NOT NULL REFERENCES chat.users(id) ON DELETE CASCADE,
	roomID INT NOT NULL REFERENCES chat.chatrooms(id) ON DELETE CASCADE,
	text TEXT NOT NULL,
	date TIMESTAMP NOT NULL 
);