CREATE SCHEMA IF NOT EXISTS Chat;

CREATE TABLE Chat.users (
	id SERIAL PRIMARY KEY,
	login TEXT NOT NULL UNIQUE,
	password TEXT
);

CREATE TABLE Chat.chatrooms (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	owner INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE Chat.users_chatrooms (
	userID INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	chatroomID INT NOT NULL REFERENCES chatrooms(id) ON DELETE CASCADE
)


CREATE TABLE Chat.messages (
	id SERIAL PRIMARY KEY,
	authoriD INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	roomID INT NOT NULL REFERENCES chatrooms(id) ON DELETE CASCADE,
	text NOT NULL TEXT,
	date NOT NULL TEXT 
);